# Generated by Django 5.2.13 on 2026-04-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmspollplugin',
            name='choice_1',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmspollplugin',
            name='choice_2',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
